package urls

import (
	"risk-ext/app"
	"risk-ext/views"
)

func init() {
	amountView := new(views.AmountView)
	logView := new(views.LogView)
	reportView := new(views.ReportView)
	shareView := new(views.SharesView)
	commonView := new(views.CommonsView)
	simView := new(views.SimView)
	creditView := new(views.CreditView)
	dianhuaView := new(views.DianhuaView)
	userView := new(views.UsersView)
	deviceView := new(views.DevicesView)
	alarmView := new(views.AlarmsView)
	routeView := new(views.RoutesView)
	stayView := new(views.StayView)
	commandView := new(views.CommandView)
	travelView := new(views.TravelView)
	wsView := views.NewWs()

	alarmViewForApp := new(views.AlarmsViewForApp)
	commandViewForApp := new(views.CommandViewForApp)
	deviceViewForApp := new(views.DevicesViewForApp)
	routeViewForApp := new(views.RoutesViewForApp)
	stayViewForApp := new(views.StayViewForApp)
	travelViewForApp := new(views.TravelViewForApp)
	userViewForApp := new(views.UsersViewForApp)
	userViewForWX := new(views.UsersViewForWX)
	warrantiesView := new(views.WarrantiesView)
	fileUploadView := new(views.FileUploadView)

	app.AddPath("amount/", amountView)
	app.AddPath("log/", logView)
	app.AddPath("reports/", reportView)
	app.AddPath("reports/{report_id}", reportView)
	app.AddPath("shares/", shareView)
	app.AddPath("shares/{params}", shareView)
	app.AddPath("commons/", commonView)
	app.AddPath("commons/{report_id}", commonView)
	app.AddPath("sim/", simView)
	app.AddPath("credits/report", creditView)
	app.AddPath("credits/reports/review", creditView)
	app.AddPath("credits/action", creditView)
	app.AddPath("dianhua/flow", dianhuaView)
	app.AddPath("dianhua/login", dianhuaView)
	app.AddPath("user/detail", userView)
	app.AddPath("user/bind", userView)
	app.AddPath("user/fortify", userView)
	app.AddPath("user/active", userView)
	app.AddPath("user/wxlogin/{code}", userView)
	app.AddPath("devices/active", deviceView)
	app.AddPath("devices/detail", deviceView)
	app.AddPath("devices/checkdev/{qrcodeStr}", deviceView)
	app.AddPath("alarms/detail", alarmView)
	app.AddPath("alarms/list", alarmView)
	app.AddPath("routes/list", routeView)
	app.AddPath("stay/list", stayView)
	app.AddPath("command/send", commandView)
	app.AddPath("travel/delete", travelView)
	app.AddPath("travel/edit", travelView)
	app.AddPath("driver/data", wsView)

	app.AddPath("app/user/detail", userViewForApp)
	app.AddPath("app/user/bind", userViewForApp)
	app.AddPath("app/user/fortify", userViewForApp)
	app.AddPath("app/user/active", userViewForApp)
	app.AddPath("app/user/wxlogin/{code}", userViewForApp)
	app.AddPath("app/devices/active", deviceViewForApp)
	app.AddPath("app/devices/detail", deviceViewForApp)
	app.AddPath("app/devices/checkdev/{qrcodeStr}", deviceViewForApp)
	app.AddPath("app/alarms/detail", alarmViewForApp)
	app.AddPath("app/alarms/list", alarmViewForApp)
	app.AddPath("app/routes/list", routeViewForApp)
	app.AddPath("app/stay/list", stayViewForApp)
	app.AddPath("app/command/send", commandViewForApp)
	app.AddPath("app/travel/delete", travelViewForApp)
	app.AddPath("app/travel/edit", travelViewForApp)
	app.AddPath("app/travel/list", travelViewForApp)

	app.AddPath("wx/user/wxlogin/{code}", userViewForWX)

	app.AddPath("warranty/list/{id}", warrantiesView) //id 不为空获取单个信息 id为空获取列表
	app.AddPath("warranty/list", warrantiesView)
	app.AddPath("warranty/add/{step}", warrantiesView) //添加保单信息 step=1添加用户信息  step=2添加车辆信息
	app.AddPath("warranty/upload", fileUploadView)     //上传图片
}
