package urls

import (
	"risk-ext/app"
	"risk-ext/views"
)

func init() {
	amountView := new(views.AmountView)
	logView := new(views.LogView)
	reportView := new(views.ReportView)
	shareView := new(views.SharesView)
	commonView := new(views.CommonsView)
	simView := new(views.SimView)
	creditView := new(views.CreditView)
	dianhuaView := new(views.DianhuaView)
	userView := new(views.UsersView)
	deviceView := new(views.DevicesView)
	alarmView := new(views.AlarmsView)
	routeView := new(views.RoutesView)
	stayView := new(views.StayView)
	commandView := new(views.CommandView)
	travelView := new(views.TravelView)

	alarmViewForApp := new(views.AlarmsViewForApp)
	commandViewForApp := new(views.CommandViewForApp)
	deviceViewForApp := new(views.DevicesViewForApp)
	routeViewForApp := new(views.RoutesViewForApp)
	stayViewForApp := new(views.StayViewForApp)
	travelViewForApp := new(views.TravelViewForApp)
	userViewForApp := new(views.UsersViewForApp)
	userViewForWX := new(views.UsersViewForWX)

	app.AddPath("v2/amount/", amountView)
	app.AddPath("v2/log/", logView)
	app.AddPath("v2/reports/", reportView)
	app.AddPath("v2/reports/{report_id}", reportView)
	app.AddPath("v2/shares/", shareView)
	app.AddPath("v2/shares/{params}", shareView)
	app.AddPath("v2/commons/", commonView)
	app.AddPath("v2/commons/{report_id}", commonView)
	app.AddPath("v2/sim/", simView)
	app.AddPath("v2/credits/report", creditView)
	app.AddPath("v2/credits/reports/review", creditView)
	app.AddPath("v2/credits/action", creditView)
	app.AddPath("v2/dianhua/flow", dianhuaView)
	app.AddPath("v2/dianhua/login", dianhuaView)
	app.AddPath("v2/user/detail", userView)
	app.AddPath("v2/user/bind", userView)
	app.AddPath("v2/user/fortify", userView)
	app.AddPath("v2/user/active", userView)
	app.AddPath("v2/user/wxlogin/{code}", userView)
	app.AddPath("v2/devices/active", deviceView)
	app.AddPath("v2/devices/detail", deviceView)
	app.AddPath("v2/devices/checkdev/{qrcodeStr}", deviceView)
	app.AddPath("v2/alarms/detail", alarmView)
	app.AddPath("v2/alarms/list", alarmView)
	app.AddPath("v2/routes/list", routeView)
	app.AddPath("v2/stay/list", stayView)
	app.AddPath("v2/command/send", commandView)
	app.AddPath("v2/travel/delete", travelView)
	app.AddPath("v2/travel/edit", travelView)

	app.AddPath("v2/app/user/detail", userViewForApp)
	app.AddPath("v2/app/user/bind", userViewForApp)
	app.AddPath("v2/app/user/fortify", userViewForApp)
	app.AddPath("v2/app/user/active", userViewForApp)
	app.AddPath("v2/app/user/wxlogin/{code}", userViewForApp)
	app.AddPath("v2/app/devices/active", deviceViewForApp)
	app.AddPath("v2/app/devices/detail", deviceViewForApp)
	app.AddPath("v2/app/devices/checkdev/{qrcodeStr}", deviceViewForApp)
	app.AddPath("v2/app/alarms/detail", alarmViewForApp)
	app.AddPath("v2/app/alarms/list", alarmViewForApp)
	app.AddPath("v2/app/routes/list", routeViewForApp)
	app.AddPath("v2/app/stay/list", stayViewForApp)
	app.AddPath("v2/app/command/send", commandViewForApp)
	app.AddPath("v2/app/travel/delete", travelViewForApp)
	app.AddPath("v2/app/travel/edit", travelViewForApp)
	app.AddPath("v2/app/travel/list", travelViewForApp)

	app.AddPath("v2/wx/user/detail", userViewForWX)
}
